apiVersion: v1
   kind: Service
   metadata:
     name: mcp-immo-ia-service
     namespace: mcp-immo-ia-patricia-promise
   spec:
     type: NodePort
     selector:
       app: mcp-immo-ia
     ports:
       - protocol: TCP
         port: 8000
         targetPort: 8000
